# Generated by Django 5.0.1 on 2024-01-17 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("devtools", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Idea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "updated_date",
                    models.DateTimeField(
                        auto_created=True, auto_now=True, verbose_name="수정일"
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(
                        auto_created=True, auto_now_add=True, verbose_name="작성일"
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="아이디어명")),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="idea_images/%Y%m%d"
                    ),
                ),
                ("content", models.TextField(verbose_name="아이디어 설명")),
                ("interest", models.IntegerField(default=0, verbose_name="아이디어 관심도")),
                (
                    "devtool",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="idea",
                        to="devtools.devtool",
                        verbose_name="예상 개발툴",
                    ),
                ),
            ],
        ),
    ]
