# Generated by Django 5.0.1 on 2024-01-16 13:23

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Idea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="idea_images/%Y%m%d"
                    ),
                ),
                ("content", models.TextField()),
                ("interest", models.IntegerField(default=0)),
            ],
        ),
    ]
