# Generated by Django 5.0.1 on 2024-01-16 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("devtools", "0002_rename_type_devtool_kind_alter_devtool_content"),
        ("ideas", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="idea",
            name="devtool",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="devtools.devtool",
            ),
            preserve_default=False,
        ),
    ]
