# Generated by Django 5.0.1 on 2024-01-16 15:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("devtools", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="devtool",
            old_name="type",
            new_name="kind",
        ),
        migrations.AlterField(
            model_name="devtool",
            name="content",
            field=models.TextField(verbose_name="개발툴 설명"),
        ),
    ]
